language: java

jdk:
  - oraclejdk7

env:
  global:
  - GH_REF: github.com/dita4publishers/docs
  - BRANCH: master
  - DITAMAP: docs/user_docs/d4p-users-guide.ditamap
  - TRANSTYPE: d4p-html5
  - D4P_REPO: https://github.com/dita4publishers/dita4publishers.git
  - GIT_USERNAME: "Travis CI"
  - GIT_EMAIL: "travis@dita4publishers.com"
  - secure: "lLc0UVPtc7jdo2QPsc/SSQgdhmYIdQ3alkXjQttIUYC+T3S+8ol7DtBqQZ6jWLOxhVIwfFz4fNf/NtmnME/Yf304Q+KWcQE2NXyKwII/9r994QIeHTyOR5pYdCHUIs/oLbDUIg7bssgJFpqBAqJPBvs6nJCIzhHIR3sFEIoiCRo="

script: 
  - set -e
  - cd
  - git clone -b doc-engine $D4P_REPO dita4publishers
  - source ./dita4publishers/travis/doc-engine-install.sh
